### PR TITLE
add missing gulp and gulp-npm for tooling week

### PR DESCRIPTION
**Pull request by oliward**
Caused some issues today, especially on Windows (where people had forgotten their WSL root passwords!!!)

### CODE REVIEW

**Comment by smallhadroncollider** [comment]
You'll need to do a second commit to update the script download links in the README files to use the newest commit number.

And maybe add a comment to the Windows readme about picking a sensible password and make sure they remember it?

**Comment by smallhadroncollider** [comment]
If `gulp` works the same as grunt then there's no point in installing `gulp` initially as it's on a per-project basis. The setup scripts are only for global installs.

**Comment by KyeBuff** [comment]
Gulp can be installed globally, which I've done as it's a pain otherwise.

Also says in the Gulp docs (https://github.com/gulpjs/gulp/blob/master/docs/getting-started/1-quick-start.md) that the CLI tools are installed like this:

```
npm install --global gulp-cli
```

rather than

```
sudo npm install gulp-cli -g
```

**Comment by smallhadroncollider** [comment]
This line `sudo npm install gulp -D` installs gulp in the current directory doesn't it?

**Pull request merged**
